version: "3"
services:
  answerhub-test:
    volumes:
      - sites:/var/www/answerhub/teamhub.home/sites
      - search:/var/lib/answerhub/search_index
    image: registry.company.tld/answerhub:1.6.6-custom-2
    ports:
      - 8080:8080
    restart: always
    env_file:
      - secrets/test.env
    environment:
      CATALINA_OPTS: -Ddatabase.url=192.168.1.1 -Ddatabase.name=answerhub -Ddatabase.user=answerhub

volumes:
  sites:
  search:
