version: "3"
services:
  curl:
    build:
      context: .
      dockerfile: centos/7/curl/Dockerfile
    image: centos:7-curl
  scm:
    build:
      context: .
      dockerfile: centos/7/scm/Dockerfile
    image: centos:7-scm
  jdk:
    build:
      context: .
      dockerfile: centos/7/openjdk/8//Dockerfile
    image: centos:7-jdk-8
  tomcat:
    build:
      context: .
      dockerfile: centos/7/tomcat/Dockerfile
    image: centos:7-tomcat
  answerhub:
    build:
      context: .
      dockerfile: centos/7/answerhub/Dockerfile
    image: centos:7-answerhub
  answerhub-test:
    build:
      context: .
    image: centos:7-answerhub-env
    network_mode: "host"
    env_file:
      - secrets/test.env
    environment:
      CATALINA_OPTS: -Ddatabase.url=127.0.0.1 -Ddatabase.name=answerhub -Ddatabase.user=answerhub
