version: "3"
services:
  answerhub:
    build:
      context: base
      args:
       APP_VERSION: 1.6.6
    image: answerhub:base
  answerhub-test:
    volumes:
      - sites:/var/www/answerhub/teamhub.home/sites
    build:
      context: custom
    depends_on:
      - answerhub
    image: answerhub:custom
    network_mode: "host"
    env_file:
      - secrets/test.env
    environment:
      CATALINA_OPTS: -Ddatabase.url=127.0.0.1 -Ddatabase.name=answerhub -Ddatabase.user=answerhub

volumes:
  sites:
